services:
    api:
        build:
            context: .
            target: development
            dockerfile: Dockerfile
        command: >
            sh -c "pnpm run migrate:local &&
            pnpm run start:dev"
        restart: always
        depends_on:
            - mysql
        env_file:
            - .env
        ports:
            - '3000:${PORT}'
        volumes:
            - .:/usr/src/app
        networks:
            - container-network
    mysql:
        image: mysql
        env_file:
            - .env
        ports:
            - '3306:3306'
        networks:
            - container-network

networks:
    container-network:
        driver: bridge
