services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        command: >
            sh -c "pnpm run prisma:migrate &&
            pnpm run start:dev"
        restart: always
        depends_on:
            - pg
        env_file:
            - .env
        ports:
            - '3000:3000'
        volumes:
            - .:/usr/src/app
        networks:
            - container-network
    pg:
        image: postgres
        env_file:
            - .env
        ports:
            - '5432:5432'
        networks:
            - container-network

networks:
    container-network:
        driver: bridge
