services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        command: >
            sh -c "pnpm run migrate:local &&
            pnpm run start:prod"
        restart: always
        depends_on:
            - mysql
        env_file:
            - .env
        ports:
            - '3000:${PORT}'
        networks:
            - container-network
    mysql:
        image: mysql
        env_file:
            - .env
        ports:
            - '3306:3306'
        networks:
            - container-network

networks:
    container-network:
        driver: bridge
